version: 2
layout: horizontal
background_color: blue
title: My Docker Project
compose_files:
  - $TEST_PROJECT_PATH/docker-compose.yml
  - $TEST_PROJECT_PATH/docker-compose.override.yml
boxes:
  all:
    main: true
    name: Services
    size: big
    show_revision: true
    watch_branch: origin/staging
    port_view: column
    watch_for_build_using_files:
      - Dockerfile
    watch_for_build_using_git:
      - flask
  workers:
    name: Workers
    size: big
    show_git: false
    port_view: name
    includes:
      - worker
      - redis
    categories:
      - Redis
    watch_for_build_using_files:
      - Dockerfile
  devops:
    name: Devops
    size: small
    watch_branch: origin/master
    port_view: column
    includes:
      - Postgres
ignore_services:
  - portainer
watchers:
  global_success: OK
  global_error: NEED UPDATE
  ping:
    ngrok:
      name: Ngrok Access
      address: http://localhost:4040
      message_on_success: UP
      message_on_error: DOWN
  file_watch:
    cabrita:
      name: cabrita.yml
      dest_path: $TEST_PROJECT_PATH/config
      source_path: $TEST_PROJECT_PATH
      source_name: cabrita-v1.yml
